services:
    push.stat.service.inotify_manager:
        class: Push\StatBundle\Service\InotifyManager
        arguments:
            - '@rs_queue.producer'
            - '@logger'

    push.stat.service.word_manager:
        class: Push\StatBundle\Service\WordManager
        arguments:
            - '@doctrine'
            - '@logger'